# Generated by Django 4.2.4 on 2023-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='textContent',
            field=models.CharField(default='lorem ipsum dolor set', max_length=500),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='videoURL',
            field=models.URLField(default='youtube.com'),
        ),
        migrations.AddField(
            model_name='student',
            name='passwd',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='passwd',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
