# Generated by Django 4.2.4 on 2023-08-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coursecontent_textcontent_coursecontent_videourl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='videoURL',
            field=models.URLField(default='example.com'),
        ),
    ]
