# Generated by Django 4.1.7 on 2023-08-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_answer_student_question_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentlog',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
