# Generated by Django 4.1.7 on 2023-08-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_enrollmentlog_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=100)),
                ('q1A', models.CharField(max_length=100)),
                ('q1B', models.CharField(max_length=100)),
                ('q1C', models.CharField(max_length=100)),
                ('q1D', models.CharField(max_length=100)),
                ('correctAns', models.IntegerField(default=3)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
